server:
  port: 8081

spring:
  application:
    name: USER-SERVICE
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    url: jdbc:h2:mem:test1
    username: sa
    password:
    driverClassName: org.h2.Driver
    
 #for insert command in data.sql to work
  jpa:
    defer-datasource-initialization: true
    

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost
    prefer-ip-address: true