server:
  port: 8081

spring:
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    url: jdbc:h2:mem:test1
    username: sa
    password:
    driverClassName: org.h2.Driver
    
 #for insert command in data.sql to work
  jpa:
    defer-datasource-initialization: true